/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./erc20.sol";
export type { erc20Sol };
import type * as htlcSol from "./htlc.sol";
export type { htlcSol };
